# config/docker.yaml
persistence:
  defaultStore: sqlite
  visibilityStore: visibility
  numHistoryShards: 3
  sqlite:
    dataSource: file:temporal.db  # Specify the SQLite database file path

services:
  frontend:
    rpc:
      port: 7233
  matching:
    rpc:
      port: 7234

# Add other configurations as needed for your specific setup
