"""optional workflow params

Revision ID: 588bf9d4ab7a
Revises: 5b1c4391600d
Create Date: 2025-04-29 17:06:40.649720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588bf9d4ab7a'
down_revision: Union[str, None] = '5b1c4391600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'workflow_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agents', 'workflow_queue_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'workflow_queue_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agents', 'workflow_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
