"""update api keys

Revision ID: a3a5873491af
Revises: 356ff27e3095
Create Date: 2025-07-31 19:36:41.463877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a5873491af'
down_revision: Union[str, None] = '356ff27e3095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM agent_api_keys
    """)
    op.add_column('agent_api_keys', sa.Column('api_key', sa.String(), nullable=False))
    op.drop_column('agent_api_keys', 'api_key_hash')
    op.create_index(op.f('ix_agent_api_keys_api_key'), 'agent_api_keys', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM agent_api_keys
    """)
    op.add_column('agent_api_keys', sa.Column('api_key_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agent_api_keys_api_key'), table_name='agent_api_keys')
    op.drop_column('agent_api_keys', 'api_key')
    # ### end Alembic commands ###
