"""update_acp_type_default_to_async

Revision ID: a1b2c3d4e5f6
Revises: d7addd4229e8
Create Date: 2025-10-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'd7addd4229e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change the server default from 'agentic' to 'async' for new agents
    # Note: This does NOT migrate existing data, they keep their current value
    op.alter_column('agents', 'acp_type', 
                    server_default='async',
                    existing_type=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the server default back to 'agentic'
    op.alter_column('agents', 'acp_type',
                    server_default='agentic',
                    existing_type=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###

