"""agent api keys

Revision ID: 356ff27e3095
Revises: b17f16df0fbb
Create Date: 2025-07-25 17:24:31.076478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356ff27e3095'
down_revision: Union[str, None] = 'b17f16df0fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_api_keys',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('api_key_type', sa.Enum('INTERNAL', 'EXTERNAL', name='agentapikeytype'), nullable=False),
        sa.Column('api_key_hash', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
        sa.PrimaryKeyConstraint('id', 'agent_id')
    )
    op.create_index('idx_agent_api_keys_agent', 'agent_api_keys', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_api_keys_name'), 'agent_api_keys', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_api_keys_name'), table_name='agent_api_keys')
    op.drop_index('idx_agent_api_keys_agent', table_name='agent_api_keys')
    op.drop_table('agent_api_keys')
    # ### end Alembic commands ###
