"""soft delete status

Revision ID: d7addd4229e8
Revises: 09368a02d6cc
Create Date: 2025-10-17 00:06:45.407555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7addd4229e8'
down_revision: Union[str, None] = '09368a02d6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE taskstatus ADD VALUE IF NOT EXISTS 'DELETED';
    """)
    op.execute("""
        ALTER TYPE agentstatus ADD VALUE IF NOT EXISTS 'DELETED';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
