"""add_performance_indexes

Revision ID: d024851e790c
Revises: 24429f13b8bd
Create Date: 2025-12-24 20:23:00.061860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd024851e790c'
down_revision: Union[str, None] = '24429f13b8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_index('ix_spans_parent_id', 'spans', ['parent_id'], unique=False)
    op.create_index('ix_spans_trace_id', 'spans', ['trace_id'], unique=False)
    op.create_index('ix_spans_trace_id_start_time', 'spans', ['trace_id', 'start_time'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_spans_trace_id_start_time', table_name='spans')
    op.drop_index('ix_spans_trace_id', table_name='spans')
    op.drop_index('ix_spans_parent_id', table_name='spans')
    op.drop_index('ix_agents_status', table_name='agents')
    # ### end Alembic commands ###
