"""add agent input type

Revision ID: 24429f13b8bd
Revises: a5d67f2d7356
Create Date: 2025-11-04 23:40:10.340272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24429f13b8bd'
down_revision: Union[str, None] = 'a5d67f2d7356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic doesn't create enum types on table updates, so we need to do it manually
    op.execute("""
    DO $$
        BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agentinputtype') THEN
            CREATE TYPE agentinputtype AS ENUM ('TEXT', 'JSON');
        END IF;
    END $$;
    """)
    op.add_column('agents', sa.Column('agent_input_type', sa.Enum('TEXT', 'JSON', name='agentinputtype', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_input_type')
    # ### end Alembic commands ###
