"""registration metadata

Revision ID: 739800d3e1ce
Revises: dbac39ab82c3
Create Date: 2025-09-08 22:03:22.602779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '739800d3e1ce'
down_revision: Union[str, None] = 'dbac39ab82c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('registration_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'registered_at')
    op.drop_column('agents', 'registration_metadata')
    # ### end Alembic commands ###
