"""github api keys

Revision ID: 09916d346af6
Revises: a3a5873491af
Create Date: 2025-08-08 19:32:48.341998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09916d346af6'
down_revision: Union[str, None] = 'a3a5873491af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE agentapikeytype ADD VALUE IF NOT EXISTS 'GITHUB';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
