"""acp_url

Revision ID: 5b1c4391600d
Revises: 1718c7749b91
Create Date: 2025-04-28 18:10:06.447864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1c4391600d'
down_revision: Union[str, None] = '1718c7749b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('acp_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'acp_url')
    # ### end Alembic commands ###
