"""change_default_acp_to_async

Revision ID: 329fbafa4ff9
Revises: d7addd4229e8
Create Date: 2025-11-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329fbafa4ff9'
down_revision: Union[str, None] = 'd7addd4229e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change the server_default of acp_type column to "async"
    op.alter_column(
        'agents',
        'acp_type',
        server_default='async',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the server_default of acp_type column back to "agentic"
    op.alter_column(
        'agents',
        'acp_type',
        server_default='agentic',
        existing_nullable=False
    )
    # ### end Alembic commands ###

