"""add_acp_type_to_agents

Revision ID: 7736391266fa
Revises: e7bab805840b
Create Date: 2025-06-15 05:16:57.205927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7736391266fa'
down_revision: Union[str, None] = 'e7bab805840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('acp_type', sa.String(), server_default='agentic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'acp_type')
    # ### end Alembic commands ###
