"""add unhealthy status

Revision ID: a5d67f2d7356
Revises: 329fbafa4ff9
Create Date: 2025-11-04 19:23:22.904744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d67f2d7356'
down_revision: Union[str, None] = '329fbafa4ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE agentstatus ADD VALUE IF NOT EXISTS 'UNHEALTHY';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
