"""slack api key type

Revision ID: 17c57fe68d04
Revises: 09916d346af6
Create Date: 2025-08-13 17:47:46.898781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c57fe68d04'
down_revision: Union[str, None] = '09916d346af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE agentapikeytype ADD VALUE IF NOT EXISTS 'SLACK';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
