"""deployment history

Revision ID: 09368a02d6cc
Revises: 739800d3e1ce
Create Date: 2025-10-01 23:37:20.259027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09368a02d6cc'
down_revision: Union[str, None] = '739800d3e1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('build_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployment_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id', 'agent_id')
    )
    op.create_index('idx_deployment_history_agent', 'deployment_history', ['agent_id'], unique=False)
    op.create_index('ix_deployment_history_commit_hash', 'deployment_history', ['commit_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deployment_history_commit_hash', table_name='deployment_history')
    op.drop_index('idx_deployment_history_agent', table_name='deployment_history')
    op.drop_table('deployment_history')
    # ### end Alembic commands ###
