"""postgres messages

Revision ID: b4d5f54e4ba2
Revises: 07fc12196914
Create Date: 2026-02-10 17:53:14.889515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4d5f54e4ba2'
down_revision: Union[str, None] = '07fc12196914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('streaming_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_messages_task_id', 'task_messages', ['task_id'], unique=False)
    op.create_index('idx_task_messages_task_id_created_at', 'task_messages', ['task_id', 'created_at'], unique=False)
    op.create_index('idx_task_messages_task_id_streaming_status', 'task_messages', ['task_id', 'streaming_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_messages_task_id_streaming_status', table_name='task_messages')
    op.drop_index('idx_task_messages_task_id_created_at', table_name='task_messages')
    op.drop_index('idx_task_messages_task_id', table_name='task_messages')
    op.drop_table('task_messages')
    # ### end Alembic commands ###
