"""add build_only agent status

Revision ID: c7a1b2d3e4f5
Revises: 6c942325c828
Create Date: 2026-05-29 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a1b2d3e4f5'
down_revision: Union[str, None] = '6c942325c828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE agentstatus ADD VALUE IF NOT EXISTS 'BUILD_ONLY';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres does not support removing a value from an enum type, so there is
    # nothing to do on downgrade (mirrors the add_unhealthy_status migration).
    # ### end Alembic commands ###
    pass
